apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: dev
  labels:
    app: mongo-express
spec:
  ports:
    - name: http
      port: 8081
  selector:
    app: mongo-express
  type: LoadBalancer
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: dev
  labels:
    app: mongo-express
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: mongo-express
          # image: mongo-express
          image: mongo-express:1.0.0-alpha.4
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
          env:
            # - name: ME_CONFIG_MONGODB_URL
            #   value: "mongodb://username:password@mongo-service.dev:27017/admin"
            # - name: ME_CONFIG_MONGODB_PORT
            #   value: !!integer "27017"
            # - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            #   value: "admin"
            # - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            #   value: "username"
            # - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            #   value: "password"
            # - name: ME_CONFIG_MONGODB_PORT
            #   value: !!integer "27017"
            # - name: ME_CONFIG_MONGODB_SERVER
            #   value: "mongo-service.dev"
            # - name: ME_CONFIG_MONGODB_SERVER
            #   value: "mongo-service.dev.svc.cluster.local,mongo-service.dev"
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: mongodb.host
            - name: ME_CONFIG_MONGODB_PORT
              value: !!integer "27017"
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: mongodb.username
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: mongodb.password
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: me.basicauth.username
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: me.basicauth.password
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: mongodb.username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-config
                  key: mongodb.password
